import { Raleway } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Asifur Rahman | Full Stack Developer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${raleway.variable} h-full antialiased`}
      data-theme="dark"
    >
      <body className="">
        {children}
        <Toaster
          toastOptions={{
            className: "glass-bg !text-white backdrop-blur-xl",
            style: {
              background: "transparent",
              boxShadow: "none",
              color : "none"
            },
          }}
        />
      </body>
    </html>
  );
}
